
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit=11.7.1
  - efficientnet-pytorch=0.7.1
  - numpy-base=1.23.3
  - python=3.10.6
  - pytorch=1.13.0
  - tqdm=4.64.1
  - yaml=0.2.5
  - pip:
    - albumentations==1.3.0
    - anndata==0.9.1
    - boto3==1.24.96
    - botocore==1.27.96
    - docker==6.1.3
    - gtfparse==1.2.1
    - h5py==3.7.0
    - hydra-core==1.2.0
    - matplotlib==3.7.1
    - numpy==1.22.4
    - omegaconf==2.2.3
    - opencv-python-headless==4.6.0.66
    - pandas==1.4.3
    - pillow==9.2.0
    - pip==22.2.2
    - protobuf==4.23.3
    - pytest==7.1.3
    - pytest-cov==3.0.0
    - pyyaml==6.0
    - scanpy==1.9.3
    - scikit-image==0.19.3
    - scikit-learn==1.1.3
    - seaborn==0.12.2
    - setuptools==65.5.0
    - slingpy==0.4.8
    - statsmodels==0.14.0
    - tifffile==2022.10.10
    - torch==1.13.0
    - torchvision==0.14.0
    - umap-learn==0.5.3

